### ISSUE TITLE
Site has headerbar and content colors swapped

### ISSUE THREAD

**Issue by polyjitter** [GeopJr/libadwaita.cr#2]
See:
![image](https://user-images.githubusercontent.com/18127936/179304880-5538fcd3-fc04-4073-b7a5-7ec7eff0d2c4.png)

**Comment by polyjitter** [comment]
Light theme is also slightly off:

![image](https://user-images.githubusercontent.com/18127936/179305028-58fa513b-1c13-4a6e-ab7b-a679c8678498.png)

**Comment by GeopJr** [comment]
Thanks for letting me know!

These colors are remnants of libadwaita alpha, I went ahead and updated them (+ did some general upkeeping with Svelte & others), it should be up in a few minutes!
